### ISSUE TITLE
ArrayIndexOutOfBounds in ChunkReloader

### ISSUE THREAD

**Issue by Asgarioth** [lishid/Orebfuscator#100]
I saw one Exception thrown by Orebfuscator in my logs out of nowhere. It neither caused any harm nor detectable malfunction. Nevertheless you might be interested. ;)

`[18:01:51] [Orebfuscator ChunkReloader Thread/ERROR]: [OFC] java.lang.ArrayIndexOutOfBoundsException: 21
[18:01:51] [Orebfuscator ChunkReloader Thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 21
[18:01:51] [Orebfuscator ChunkReloader Thread/WARN]: 	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:374)
[18:01:51] [Orebfuscator ChunkReloader Thread/WARN]: 	at net.minecraft.server.v1_9_R2.PlayerChunkMap.getChunk(PlayerChunkMap.java:216)
[18:01:51] [Orebfuscator ChunkReloader Thread/WARN]: 	at net.minecraft.server.v1_9_R2.PlayerChunkMap.isChunkInUse(PlayerChunkMap.java:241)
[18:01:51] [Orebfuscator ChunkReloader Thread/WARN]: 	at com.lishid.orebfuscator.nms.v1_9_R2.ChunkManager.canResendChunk(ChunkManager.java:28)
[18:01:51] [Orebfuscator ChunkReloader Thread/WARN]: 	at com.lishid.orebfuscator.obfuscation.ChunkReloader.reloadChunks(ChunkReloader.java:138)
[18:01:51] [Orebfuscator ChunkReloader Thread/WARN]: 	at com.lishid.orebfuscator.obfuscation.ChunkReloader.run(ChunkReloader.java:113)`

**Comment by ProgrammerDan** [comment]
Thank you for the report! To help us investigate, which version/fork of CraftBukkit are you using, and which release of Orebfuscator are you using? Thank you!

**Comment by Asgarioth** [comment]
Oops... sorry for that. I lost some lines while pasting the text. ;)

Spigot build is: git-Spigot-8a048fe-a022dd2 (MC: 1.9.4) along with the latest (4.0.14-SNAPSHOT) Orebfuscator release.

**Comment by Aleksey-Terzi** [comment]
Bug should be fixed in the latest (4.1.1) release, therefore I'm closing this issue.
Please reopen it if you will encounter the same problem with latest update,
