### ISSUE TITLE
ChunkReloader Thread/ERROR

### ISSUE THREAD

**Issue by dadee971** [lishid/Orebfuscator#110]
Hi,
I have this error sometime in console.
But OFC is working normally.

[09:56:44] [Orebfuscator ChunkReloader Thread/ERROR]: [OFC] java.lang.ArrayIndexOutOfBoundsException
[09:56:44] [Orebfuscator ChunkReloader Thread/WARN]: java.lang.ArrayIndexOutOfBoundsException

**Comment by RoboMWM** [comment]
Is there anything more in console to this error? (Although I do recall seeing this error appear in console for no reason - I only got a stack trace when the player logged in an area with over 128 blocks vs. entering the area/teleporting to it via a nether portal.)

**Comment by ProgrammerDan** [comment]
Another player reports similar:

```
Exception occured

[18:17:51] [Orebfuscator ChunkReloader Thread/ERROR]: [OFC] java.lang.ArrayIndexOutOfBoundsException: 1801
[18:17:51] [Orebfuscator ChunkReloader Thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1801
[18:17:51] [Orebfuscator ChunkReloader Thread/WARN]: at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:374)
[18:17:51] [Orebfuscator ChunkReloader Thread/WARN]: at net.minecraft.server.v1_10_R1.PlayerChunkMap.getChunk(PlayerChunkMap.java:216)
[18:17:51] [Orebfuscator ChunkReloader Thread/WARN]: at net.minecraft.server.v1_10_R1.PlayerChunkMap.isChunkInUse(PlayerChunkMap.java:241)
[18:17:51] [Orebfuscator ChunkReloader Thread/WARN]: at com.lishid.orebfuscator.nms.v1_10_R1.ChunkManager.canResendChunk(ChunkManager.java:28)
[18:17:51] [Orebfuscator ChunkReloader Thread/WARN]: at com.lishid.orebfuscator.obfuscation.ChunkReloader.reloadChunks(ChunkReloader.java:138)
[18:17:51] [Orebfuscator ChunkReloader Thread/WARN]: at com.lishid.orebfuscator.obfuscation.ChunkReloader.run(ChunkReloader.java:113)

unfortunately, I don't know how to replicate the problem

the only clue is that it happened when a player used command /home

so it sounds like related to chunk loading
```

**Comment by Aleksey-Terzi** [comment]
@dadee971

What version of Orebfuscator are you using?
If you can provide full log - that will be even better.

**Comment by dadee971** [comment]
I'm using ofc 4.1.2.
An still got the errors:

[05:19:49] [Orebfuscator ChunkReloader Thread/ERROR]: [OFC] java.lang.ArrayIndexOutOfBoundsException: 17
[05:20:05] [Orebfuscator ChunkReloader Thread/ERROR]: [OFC] java.lang.ArrayIndexOutOfBoundsException: 25
[05:21:19] [Orebfuscator ChunkReloader Thread/ERROR]: [OFC] java.lang.ArrayIndexOutOfBoundsException: 189

**Comment by Aleksey-Terzi** [comment]
Thank you for details.

**Comment by Aleksey-Terzi** [comment]
This issue is solved in latest release.
