### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by molor** [lishid/Orebfuscator#122]
Maybe this error is already reported previously, but suddenly not?
Orebfuscator 4.1.2, Spigot 1.10.2.

```
[2016-08-21 21:55:32] [OFC] java.lang.ArrayIndexOutOfBoundsException: 112
[2016-08-21 21:55:32] java.lang.ArrayIndexOutOfBoundsException: 112
[2016-08-21 21:55:32] 	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.containsKey(Long2ObjectOpenHashMap.java:389)
[2016-08-21 21:55:32] 	at net.minecraft.server.v1_10_R1.ChunkProviderServer.isLoaded(ChunkProviderServer.java:330)
[2016-08-21 21:55:32] 	at com.lishid.orebfuscator.nms.v1_10_R1.ChunkManager.canResendChunk(ChunkManager.java:31)
[2016-08-21 21:55:32] 	at com.lishid.orebfuscator.obfuscation.ChunkReloader.reloadChunks(ChunkReloader.java:138)
[2016-08-21 21:55:32] 	at com.lishid.orebfuscator.obfuscation.ChunkReloader.run(ChunkReloader.java:113)
```

**Comment by Aleksey-Terzi** [comment]
Thanks for bug report.

Yes, this bug is already posted in issue #110.

It is fixed and just need to post new release.
