### ISSUE TITLE
Error message spam in 1.8

### ISSUE THREAD

**Issue by Kira07** [lishid/Orebfuscator#138]
[22:46:44] [Netty Epoll Server IO #1/ERROR]: [Orebfuscator3] Unhandled exception number 128 occured in onPacketReceiving(PacketEvent) for Orebfuscator3
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_8_R3.PacketPlayInBlockDig$EnumPlayerDigType exists in class PacketPlayInWindowClick.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:219) ~[ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib.jar:4.1.0-b325]
	at com.lishid.orebfuscator.hook.ProtocolLibHook$2.onPacketReceiving(ProtocolLibHook.java:54) ~[orebfuscator-3.0.6-for-1.8.8-spigot.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-PaperSpigot-"8b18730"]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.1.0-b325]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by ProgrammerDan** [comment]
Just a note that we do not offer much support for Orebfuscator3-series builds. It'll be up to Aleks discretion if he attempts a debug. Since they are legacy, we officially support only 1.9.x - 1.11.

**Comment by Kira07** [comment]
Why is that ? Around 50% of the servers are using 1.8 :(
And it's by far the most popular version amongst players

**Comment by ProgrammerDan** [comment]
Mostly because Aleksey didn't do the coding and Lishid isn't involved in the project any longer. No other reasons really ... if a dev came along and wanted to dedicated to maintenancing the 1.8.x branch, I'd be honored to merge their PRs and publish builds w/ accolades.

**Comment by Aleksey-Terzi** [comment]
Sorry, but as Dan told we are not supporting Orebfuscator 3 by development.
3.x has different codebase and requires setup of different test environment and I'm not ready to start investigation of this.

Therefore I'm closing this issue.
