### ISSUE TITLE
up to date ?

### ISSUE THREAD

**Issue by comonier** [lishid/Orebfuscator#147]
please update oreb for last version of spigot: CraftBukkit version git-Spigot-625bc00-d09304e (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
from: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits (md_5 project)
spigot 1.11.2 with java 8
`[23:04:07] [Server thread/INFO]: [Orebfuscator4] Enabling Orebfuscator4 v4.2.1
[23:04:07] [Server thread/ERROR]: Error occurred while enabling Orebfuscator4 v4.2.1 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: 342
	at com.lishid.orebfuscator.config.ProximityHiderConfig.setProximityHiderBlockMatrix(ProximityHiderConfig.java:164) ~[?:?]
	at com.lishid.orebfuscator.config.ProximityHiderConfig.init(ProximityHiderConfig.java:83) ~[?:?]
	at com.lishid.orebfuscator.config.WorldConfig.init(WorldConfig.java:92) ~[?:?]
	at com.lishid.orebfuscator.config.WorldReader.readWorldByType(WorldReader.java:129) ~[?:?]
	at com.lishid.orebfuscator.config.WorldReader.load(WorldReader.java:62) ~[?:?]
	at com.lishid.orebfuscator.config.ConfigManager.load(ConfigManager.java:128) ~[?:?]
	at com.lishid.orebfuscator.Orebfuscator.loadOrebfuscatorConfig(Orebfuscator.java:98) ~[?:?]
	at com.lishid.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:71) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]`

**Comment by comonier** [comment]
found solution, after delete config.yml
