### ISSUE TITLE
I have a issue

### ISSUE THREAD

**Issue by MhaWTHoR** [lishid/Orebfuscator#182]
`[19:48:35 ERROR]: Error occurred while enabling Orebfuscator3 v3.0.6-R1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Block
        at com.lishid.orebfuscator.internal.MinecraftInternals.isBlockTransparent(MinecraftInternals.java:30) ~[?:?]
        at com.lishid.orebfuscator.OrebfuscatorConfig.generateTransparentBlocks(OrebfuscatorConfig.java:120) ~[?:?]
        at com.lishid.orebfuscator.OrebfuscatorConfig.isBlockTransparent(OrebfuscatorConfig.java:105) ~[?:?]
        at com.lishid.orebfuscator.OrebfuscatorConfig.setBlockValues(OrebfuscatorConfig.java:341) ~[?:?]
        at com.lishid.orebfuscator.OrebfuscatorConfig.load(OrebfuscatorConfig.java:414) ~[?:?]
        at com.lishid.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:57) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paper.jar:git-PaperSpigot-"4c7641d"]
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paper.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paper.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`
I use Orebfuscator 3.0.6.
ProtocolLib: 4.3.0 
PaperSpigot: 1.8.8-R0.1
Thanks.

**Comment by ProgrammerDan** [comment]
I apologize but we do not support pre 1.9 Orebfuscator at all. Those releases are provided as-is, with no guarantee or promise of support. 

However, it does appear you are simply using the _wrong_ legacy release. Please use R3 instead: https://github.com/lishid/Orebfuscator/releases/tag/v3.0.6-R3-legacy
