### ISSUE TITLE
hi, ihave problem.

### ISSUE THREAD

**Issue by successed** [lishid/Orebfuscator#192]
[19:53:28] [Server thread/INFO]: [OFC] Error while obtaining metadata for playerUNKNOWN[/127.0.0.1:51620]: The method hasMetadata is not supported for temporary players.
[19:53:28] [Server thread/WARN]: java.lang.UnsupportedOperationException: The method hasMetadata is not supported for temporary players.
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$fa316778.hasMetadata(<generated>)
[19:53:28] [Server thread/WARN]: at com.lishid.orebfuscator.config.OrebfuscatorConfig.playerBypassMetadata(OrebfuscatorConfig.java:312)
[19:53:28] [Server thread/WARN]: at com.lishid.orebfuscator.config.OrebfuscatorConfig.obfuscateForPlayer(OrebfuscatorConfig.java:283)
[19:53:28] [Server thread/WARN]: at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:54)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[19:53:28] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194)
[19:53:28] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:53:28] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:53:28] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:53:28] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:677)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$600(ChannelInjector.java:77)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$6.run(ChannelInjector.java:504)
[19:53:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[19:53:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[19:53:28] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[19:53:28] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[19:53:28] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[19:53:28] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[19:53:28] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
[19:53:28] [Server thread/WARN]: java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$fa316778.getWorld(<generated>)
[19:53:28] [Server thread/WARN]: at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:58)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[19:53:28] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194)
[19:53:28] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:53:28] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:53:28] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:53:28] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:677)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$600(ChannelInjector.java:77)
[19:53:28] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$6.run(ChannelInjector.java:504)
[19:53:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[19:53:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[19:53:28] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[19:53:28] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[19:53:28] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[19:53:28] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[19:53:28] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by ProgrammerDan** [comment]
Thank you for the report!

Can you please also post your config.yml for orebfuscator, including which version of Orebfuscator you are using, and which version of ProtocolLib, and finally, which version of Bukkit/Spigot/MC you are using?

**Comment by ProgrammerDan** [comment]
@successed If possible, please provide:

1) the config.yml you use for Orebfuscator

2) which version of Orebfuscator caused the issue

3) which version of ProtocolLib you are using

4) which version of Bukkit/Spigot/MC you are using


Thanks!

**Comment by successed** [comment]
server version: 1.13.2 T0.1-SNAPSHOT

orebfuscator version : orebfuscator-4.4.2.jar

Config file : [config.zip](https://github.com/lishid/Orebfuscator/files/2590104/config.zip)

protocollib version 4.4.0
