### ISSUE TITLE
Orebfuscator4 causes minecraft to crash after entering in to world

### ISSUE THREAD

**Issue by videosambo** [lishid/Orebfuscator#196]
So, I have spigot 1.13.1 and minecraft version that I have tested are vanilla 1.13.1 and latest Optifine 1.13.1. Both clients crashes after entering to server with orebfuscator. Im using latest update of ofc. Server doesent crash or give any error but it still causes clients crash. You can enter to world without orebfuscator and everything is working fine.
Here is the minecraft crash report:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 14.11.2018 15:23
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
    at dhp$$Lambda$1133/862562079.getColor(Unknown Source)
    at dhp.a(SourceFile:26)
    at dhp.a(SourceFile:37)
    at cgf.k(SourceFile:41)
    at cgf$$Lambda$965/1016989399.getColor(Unknown Source)
    at cgf.a(SourceFile:103)
    at cuw.a(SourceFile:134)
    at cuw.b(SourceFile:74)
    at cuw.a(SourceFile:45)
    at cuu.a(SourceFile:60)
    at cwt.b(SourceFile:199)
    at cwq.a(SourceFile:103)
    at cwp.b(SourceFile:137)
    at cue.a(SourceFile:945)
    at cty.b(SourceFile:939)
    at cty.a(SourceFile:875)
    at cty.a(SourceFile:749)
    at cft.c(SourceFile:850)
    at cft.a(SourceFile:395)
    at net.minecraft.client.main.Main.main(SourceFile:144)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at dhp$$Lambda$1133/862562079.getColor(Unknown Source)
    at dhp.a(SourceFile:26)
    at dhp.a(SourceFile:37)
    at cgf.k(SourceFile:41)
    at cgf$$Lambda$965/1016989399.getColor(Unknown Source)
    at cgf.a(SourceFile:103)
    at cuw.a(SourceFile:134)
    at cuw.b(SourceFile:74)

-- Block model being tesselated --
Details:
    Block: Block{minecraft:grass_block}[snowy=false]
    Block location: World: (-60,64,-2), Chunk: (at 4,4,14 in -4,-1; contains blocks -64,0,-16 to -49,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Using AO: true
Stacktrace:
    at cuw.a(SourceFile:45)

-- Block being tesselated --
Details:
    Block: Block{minecraft:grass_block}[snowy=false]
    Block location: World: (-60,64,-2), Chunk: (at 4,4,14 in -4,-1; contains blocks -64,0,-16 to -49,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
    at cuu.a(SourceFile:60)
    at cwt.b(SourceFile:199)
    at cwq.a(SourceFile:103)
    at cwp.b(SourceFile:137)
    at cue.a(SourceFile:945)
    at cty.b(SourceFile:939)
    at cty.a(SourceFile:875)

-- Affected level --
Details:
    Level name: MpServer
    All players: 5 total; [ctj['videosambo'/27897241, l='MpServer', x=-60.62, y=67.00, z=-9.78], ctk['Tuonela'/721, l='MpServer', x=-80.45, y=65.00, z=-44.49], ctk['Ääri'/727, l='MpServer', x=-80.54, y=65.00, z=-47.54], ctk['Säännöt'/724, l='MpServer', x=-75.50, y=65.00, z=-49.48], ctk['Rakennusmaailma'/730, l='MpServer', x=-78.54, y=65.00, z=-49.49]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: {}
    Level spawn location: World: (-61,70,-20), Chunk: (at 3,4,12 in -4,-2; contains blocks -64,0,-32 to -49,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 145656187 game time, 151072346 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 103 total; [amb['Item Frame'/256, l='MpServer', x=-56.50, y=66.50, z=-0.03], amb['Item Frame'/257, l='MpServer', x=-57.50, y=66.50, z=-0.03], amb['Item Frame'/258, l='MpServer', x=-57.50, y=67.50, z=-0.03], amb['Item Frame'/259, l='MpServer', x=-56.50, y=67.50, z=-0.03], amb['Item Frame'/260, l='MpServer', x=-55.50, y=67.50, z=-0.03], amb['Item Frame'/261, l='MpServer', x=-54.50, y=67.50, z=-0.03], amb['Item Frame'/262, l='MpServer', x=-53.50, y=67.50, z=-0.03], amb['Item Frame'/263, l='MpServer', x=-53.50, y=68.50, z=-0.03], amb['Item Frame'/264, l='MpServer', x=-54.50, y=68.50, z=-0.03], amb['Item Frame'/265, l='MpServer', x=-55.50, y=68.50, z=-0.03], amb['Item Frame'/266, l='MpServer', x=-56.50, y=68.50, z=-0.03], amb['Item Frame'/267, l='MpServer', x=-57.50, y=68.50, z=-0.03], amb['Item Frame'/268, l='MpServer', x=-57.50, y=69.50, z=-0.03], amb['Item Frame'/269, l='MpServer', x=-56.50, y=69.50, z=-0.03], amb['Item Frame'/270, l='MpServer', x=-55.50, y=69.50, z=-0.03], amb['Item Frame'/271, l='MpServer', x=-54.50, y=69.50, z=-0.03], ame['Painting'/272, l='MpServer', x=-54.50, y=74.00, z=8.03], alz['Armor Stand'/296, l='MpServer', x=-37.50, y=66.00, z=-51.50], amb['Item Frame'/297, l='MpServer', x=-43.50, y=64.50, z=-37.03], alz['Armor Stand'/298, l='MpServer', x=-34.50, y=66.00, z=-43.50], ame['Painting'/299, l='MpServer', x=-44.03, y=68.00, z=-2.50], amb['Item Frame'/300, l='MpServer', x=-46.50, y=50.03, z=1.50], amb['Item Frame'/301, l='MpServer', x=-40.50, y=50.50, z=19.97], akj['Tropical Fish'/302, l='MpServer', x=-47.41, y=62.69, z=20.49], anw['Zombie'/328, l='MpServer', x=-19.50, y=18.00, z=-48.50], amt['Creeper'/329, l='MpServer', x=-28.30, y=68.00, z=-21.49], amb['Item Frame'/330, l='MpServer', x=-30.50, y=50.03, z=-4.50], ctj['videosambo'/27897241, l='MpServer', x=-60.62, y=67.00, z=-9.78], anq['Spider'/332, l='MpServer', x=-22.50, y=64.00, z=25.50], amt['Creeper'/343, l='MpServer', x=-15.50, y=19.00, z=-1.50], amt['Creeper'/344, l='MpServer', x=-13.50, y=19.00, z=-0.50], ame['Painting'/181, l='MpServer', x=-80.00, y=74.50, z=-5.97], ame['Painting'/299, l='MpServer', x=-44.03, y=68.00, z=-2.50], ame['Painting'/272, l='MpServer', x=-54.50, y=74.00, z=8.03], ame['Painting'/186, l='MpServer', x=-79.50, y=74.00, z=3.97], ame['Painting'/187, l='MpServer', x=-79.50, y=70.50, z=1.97], ame['Painting'/188, l='MpServer', x=-77.03, y=67.00, z=1.00], ame['Painting'/190, l='MpServer', x=-69.03, y=76.50, z=5.50], ame['Painting'/191, l='MpServer', x=-77.00, y=68.50, z=5.03], ame['Painting'/159, l='MpServer', x=-83.50, y=72.50, z=-13.97], apk['Minecart'/127, l='MpServer', x=-98.36, y=75.00, z=25.49], ann['Skeleton'/128, l='MpServer', x=-102.52, y=75.00, z=30.72], ctk['Tuonela'/721, l='MpServer', x=-80.45, y=65.00, z=-44.49], ctk['Ääri'/727, l='MpServer', x=-80.54, y=65.00, z=-47.54], ajl['Bat'/156, l='MpServer', x=-82.95, y=37.00, z=-48.83], ann['Skeleton'/157, l='MpServer', x=-91.50, y=42.00, z=-35.50], amb['Item Frame'/158, l='MpServer', x=-88.97, y=65.50, z=-10.50], ame['Painting'/159, l='MpServer', x=-83.50, y=72.50, z=-13.97], ann['Skeleton'/160, l='MpServer', x=-95.50, y=55.00, z=19.50], ctk['Rakennusmaailma'/730, l='MpServer', x=-78.54, y=65.00, z=-49.49], anw['Zombie'/178, l='MpServer', x=-68.67, y=36.00, z=-38.44], amb['Item Frame'/179, l='MpServer', x=-78.50, y=80.03, z=-16.50], alz['Armor Stand'/180, l='MpServer', x=-79.50, y=65.50, z=-3.50], ame['Painting'/181, l='MpServer', x=-80.00, y=74.50, z=-5.97], amt['Creeper'/182, l='MpServer', x=-79.44, y=52.00, z=2.80], amm[''/694, l='MpServer', x=-38.50, y=64.00, z=-38.50], amt['Creeper'/183, l='MpServer', x=-77.58, y=52.00, z=5.83], amm[''/695, l='MpServer', x=-38.50, y=65.00, z=-38.50], amb['Item Frame'/184, l='MpServer', x=-67.50, y=67.50, z=10.97], amm[''/696, l='MpServer', x=-38.50, y=64.00, z=-39.50], amb['Item Frame'/185, l='MpServer', x=-79.50, y=74.50, z=1.97], amm[''/697, l='MpServer', x=-38.50, y=65.00, z=-39.50], ame['Painting'/186, l='MpServer', x=-79.50, y=74.00, z=3.97], amm[''/698, l='MpServer', x=-38.50, y=64.00, z=-40.50], ame['Painting'/187, l='MpServer', x=-79.50, y=70.50, z=1.97], amm[''/699, l='MpServer', x=-38.50, y=65.00, z=-40.50], ame['Painting'/188, l='MpServer', x=-77.03, y=67.00, z=1.00], amm[''/700, l='MpServer', x=-38.50, y=64.00, z=-41.50], amb['Item Frame'/189, l='MpServer', x=-79.50, y=75.50, z=1.97], amm[''/701, l='MpServer', x=-38.50, y=65.00, z=-41.50], ame['Painting'/190, l='MpServer', x=-69.03, y=76.50, z=5.50], amm[''/702, l='MpServer', x=-41.50, y=65.00, z=-37.50], ame['Painting'/191, l='MpServer', x=-77.00, y=68.50, z=5.03], amm[''/703, l='MpServer', x=-42.50, y=65.00, z=-37.50], amb['Item Frame'/192, l='MpServer', x=-70.03, y=72.50, z=6.50], amm[''/704, l='MpServer', x=-43.50, y=65.00, z=-37.50], amb['Item Frame'/193, l='MpServer', x=-70.03, y=71.50, z=5.50], amm[''/705, l='MpServer', x=-41.50, y=64.00, z=-37.50], amb['Item Frame'/194, l='MpServer', x=-70.03, y=71.50, z=6.50], amm[''/706, l='MpServer', x=-42.50, y=64.00, z=-37.50], amb['Item Frame'/195, l='MpServer', x=-70.03, y=72.50, z=5.50], amm[''/707, l='MpServer', x=-43.50, y=64.00, z=-37.50], amb['Item Frame'/196, l='MpServer', x=-70.03, y=73.50, z=5.50], amb['Item Frame'/197, l='MpServer', x=-70.03, y=73.50, z=6.50], amb['Item Frame'/198, l='MpServer', x=-79.50, y=66.50, z=1.97], ann['Skeleton'/199, l='MpServer', x=-73.50, y=16.00, z=37.50], ann['Skeleton'/202, l='MpServer', x=-70.50, y=63.00, z=35.50], ctk['Tuonela'/721, l='MpServer', x=-80.45, y=65.00, z=-44.49], ctk['Säännöt'/724, l='MpServer', x=-75.50, y=65.00, z=-49.48], ctk['Ääri'/727, l='MpServer', x=-80.54, y=65.00, z=-47.54], ctk['Rakennusmaailma'/730, l='MpServer', x=-78.54, y=65.00, z=-49.49], alz[''/733, l='MpServer', x=-47.97, y=68.68, z=-34.48], alz[''/734, l='MpServer', x=-47.97, y=68.43, z=-34.48], alz[''/735, l='MpServer', x=-47.97, y=68.18, z=-34.48], alz[''/736, l='MpServer', x=-53.68, y=68.68, z=-37.99], alz[''/737, l='MpServer', x=-53.68, y=68.43, z=-37.99], alz[''/738, l='MpServer', x=-53.68, y=68.18, z=-37.99], amt['Creeper'/231, l='MpServer', x=-72.50, y=80.00, z=36.50], amt['Creeper'/232, l='MpServer', x=-75.70, y=80.00, z=37.30], amb['Item Frame'/252, l='MpServer', x=-54.50, y=50.03, z=-4.50], amb['Item Frame'/253, l='MpServer', x=-53.50, y=66.50, z=-0.03], amb['Item Frame'/254, l='MpServer', x=-54.50, y=66.50, z=-0.03], amb['Item Frame'/255, l='MpServer', x=-55.50, y=66.50, z=-0.03]]
    Retry entities: 0 total; []
    Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.13-SNAPSHOT:1c5bff7:1359) <- Spigot
    Server type: Non-integrated multiplayer server
Stacktrace:
    at crg.a(SourceFile:418)
    at cft.b(SourceFile:1815)
    at cft.a(SourceFile:403)
    at net.minecraft.client.main.Main.main(SourceFile:144)

-- System Details --
Details:
    Minecraft Version: 1.13.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 506125240 bytes (482 MB) / 838860800 bytes (800 MB) up to 2147483648 bytes (2048 MB)
    JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
    Launched Version: 1.13.2
    LWJGL: 3.1.6 build 14
    OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.48, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Probably not. Jar signature remains and client brand is untouched.
    Type: Client (map_client.txt)
    Resource Packs: vanilla
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

**Comment by ProgrammerDan** [comment]
Thanks for the report, sorry for the issues -- Have passed along to Aleksey
and we'll take a look into this.

What other plugins are on the server? Is it behind Bungee? Any other
details you can provide that would help us replicate would be very useful.

**Comment by k9lego** [comment]
Are you runningPaperMC with Paper's anti-xray as well as this plugin? I found a similar issue where they conflict.
