### ISSUE TITLE
 Could not pass event BlockPistonExtendEvent to Orebfuscator4 v4.4.2

### ISSUE THREAD

**Issue by Blueeyestar** [lishid/Orebfuscator#201]
Spigot-Version: **CraftBukkit version git-Spigot-140f654-b446cb5 (MC: 1.13.2)** 

[12:07:46] [Server thread/ERROR]: Could not pass event BlockPistonExtendEvent to Orebfuscator4 v4.4.2
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[minecraft_server.jar:git-Spigot-140f654-b446cb5]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-140f654-b446cb5]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at net.minecraft.server.v1_13_R2.BlockPiston.a(BlockPiston.java:333) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at net.minecraft.server.v1_13_R2.BlockPiston.a(BlockPiston.java:189) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at net.minecraft.server.v1_13_R2.IBlockData.a(SourceFile:237) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:1105) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at net.minecraft.server.v1_13_R2.WorldServer.an(WorldServer.java:1094) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:322) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:956) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-140f654-b446cb5]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Blueeyestar** [comment]
no idea how that works...

**Comment by ProgrammerDan** [comment]
@SlimeDog Thanks. Will look into it!

**Comment by laelbe** [comment]
I have the same problem. There is a heavy EventException error.
Due to a huge server error message, I temporarily disabled the plugin.

**Comment by motherboard1999** [comment]
Yeah i have the problem to. Can you please update?

**Comment by ProgrammerDan** [comment]
I have tracked down it and another issue, in testing now. Thanks for reports.

**Comment by ProgrammerDan** [comment]
Please, everyone, download the release and let me know if it addresses this problem. If it does, I'll release on SpigotMC. Thank you!

**Comment by SlimeDog** [comment]
Spigot 1.13.2 latest (built a few minutes ago)
Orebfuscator 4.4.3

No more console/log errors, but some blocks are displayed as unknown: kelp, for example. Is that a configuration issue?

**Comment by ProgrammerDan** [comment]
Excellent question, I'll look into it. Thank you for initial testing!

**Comment by SlimeDog** [comment]
Otherwise, obfuscation looks good. I use [X-Ray Ultimate](http://resourcepack.net/x-ray-ultimate-resource-pack/) for testing.

**Comment by SlimeDog** [comment]
Probably it is an issue with X-Ray Ultimate not having the 1.13.2 blocks. It was last updated in September, and 1.13.2 was (officially) released in October. I could unzip the resource pack to verify, but I don't think it's worth the effort. For testing, it is adequate.

I think you are good to publish 4.4.3.

**Comment by ProgrammerDan** [comment]
Thank you -- seems likely, not seeing anything immediate in the config code, and on my test server I get no errors on load. 

Thanks again! I'll publish now.
