### ISSUE TITLE
Error on Blockbreakevent

### ISSUE THREAD

**Issue by CloudeLecaw** [lishid/Orebfuscator#210]
in latest spigot 1.13.2 and latest orbscurfactor you get this error if you break a block you get this error:
[code][14:56:50] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Orebfuscator4 v4.4.3
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:124) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1163) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
    at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
    at com.lishid.orebfuscator.obfuscation.BlockUpdate.update(BlockUpdate.java:69) ~[?:?]
    at com.lishid.orebfuscator.obfuscation.BlockUpdate.update(BlockUpdate.java:49) ~[?:?]
    at com.lishid.orebfuscator.listeners.OrebfuscatorBlockListener.onBlockBreak(OrebfuscatorBlockListener.java:38) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar:git-Spigot-1dc156c-4b84363]
    ... 17 more[/code]

**Comment by KarlOfDuty** [comment]
We get the same: 
![image](https://user-images.githubusercontent.com/18099825/50458002-28f27700-0960-11e9-95f6-70fc23d0518b.png)

We are running paperspigot build 488

**Comment by ProgrammerDan** [comment]
More NMS changes probably, although when I last looked at paper I saw no
difference in this area. Will look again.

**Comment by CathalCraft** [comment]
Same issue on my server too.
Latest Spigot 1.13.2 (Spigot-518206a-a5b9c7b)
Error: https://pastebin.com/MZwFpq5E

**Comment by KarlOfDuty** [comment]
If it helps this was not an issue before paper version 474 which we just upgraded from.

**Comment by ProgrammerDan** [comment]
TY yes it does

**Comment by Mante-z** [comment]
Same issue here, is there been any fix yet?

I only get it in the nether tho
And because of that i think,
When i load into the nether it takes 10 seconds to get my inventory and it gives a lag spike.
When i disable the plugin i don't get it.

**Comment by KarlOfDuty** [comment]
Yes, our players report that if you mine in the nether the obfuscation blocks don't dissapear so I assume that is related to this issue.

**Comment by Magenent** [comment]
:o

**Comment by ProgrammerDan** [comment]
Yes, been very busy with family over holidays. I will attempt to issue a
hotfix soon, the moving target on the NMS side does appear to have struck
again. Sorry for the delay.

**Comment by ghost** [comment]
> :o

:o

**Comment by Pengun78** [comment]
gamer time

**Comment by ProgrammerDan** [comment]
@ Everyone in this thread, please try https://github.com/lishid/Orebfuscator/releases/tag/4.4.4 and let me know if your situation is improved.

**Comment by ProgrammerDan** [comment]
For Paper users:

Note that in Paper, Async Chunkloading is incompatible with Orebfuscator for now. Please disable it first by modifying paper.yml and setting 
```
async-chunk:
  enabled: false
```
in the config (find the existing section and modify). Then start Paper back up (with oreb 4.4.4).

Let me know if this works.

**Comment by KarlOfDuty** [comment]
This seems to work for us, thanks!

**Comment by KarlOfDuty** [comment]
Might want to mention the paper config thing on the release too btw.

**Comment by ProgrammerDan** [comment]
It is buried in there -- I'll put it at the top on the spigot site release :) Thanks!
