### ISSUE TITLE
Spigot server crashes 1.12.2 (Exception ticking world)

### ISSUE THREAD

**Issue by DahunDev** [lishid/Orebfuscator#212]
Orebfuscator Version : 4.4.3 (for spigot 1.12.2)

ProtocolLib : 4.4.0

[13:26:01] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception ticking world
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:812) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_192]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:122) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:320) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	... 4 more
[13:26:01] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_192]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:122) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:320) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) ~[craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-2cf50f0-8166d17]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
[13:26:01] [Server thread/ERROR]: This crash report has been saved to

Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:122)
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:320)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:122)
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:320)

-- Affected level --
Details:
	Level name: Wild
	All players: 1 total; [EntityPlayer['min2e'/4403, l='Wild', x=729.61, y=72.18, z=479.30](min2e at 729.6106550111708,72.17675927506424,479.2975096590568)]
	Chunk stats: ServerChunkCache: 355 Drop: 0
	Level seed: -4481378749804099308
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (72,64,252), Chunk: (at 8,4,12 in 4,15; contains blocks 64,0,240 to 79,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 81925024 game time, 83198403 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 16706 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2016 (amd64) version 10.0
	Java Version: 1.8.0_192, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3019428880 bytes (2879 MB) / 4588568576 bytes (4376 MB) up to 11534336000 bytes (11000 MB)
	JVM Flags: 13 total; -Xms680M -Xmx11000M -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions 
	-XX:UseSSE=4 -XX:MaxGCPauseMillis=400 -XX:SurvivorRatio=4 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 
	-XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	CraftBukkit Information: 
   Running: CraftBukkit version git-Spigot-2cf50f0-8166d17 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) false

**Comment by ProgrammerDan** [comment]
I apologize, I have not had a chance yet to look through this error. Can you please list out also the other plugins you are running? it'll help isolate what is interacting with Orebfuscator to cause concurrency failures. A listing of your .jar files in the plugins folder would suffice, thank you!

**Comment by DahunDev** [comment]
Where I should post my plugin list?

**Comment by ProgrammerDan** [comment]
If nothing secret, here -- if secret, you can email me @ programmerdan @ gmail.com

**Comment by DahunDev** [comment]
I sent the plugin list to email

**Comment by DahunDev** [comment]
And What's  the correct version for 1.12.2
4.4.2 or 4.3.3

**Comment by ProgrammerDan** [comment]
looks like you have the most recent https://github.com/lishid/Orebfuscator/releases/tag/4.3.3 that's max 1.12.2 -- you could try 4.4.4 and see if it solves the issue.

Looking through the plugin list, there are many that are unfamiliar to me -- it's possible that if any other plugin creates "remaps" of chunks in server memory, it could cause a race condition with Orebfuscator. Do any other plugins also "hide" blocks or otherwise disguise blocks?

**Comment by DahunDev** [comment]
Nope, removing orebfuscator make no longer crashes.

**Comment by DahunDev** [comment]
So,Which version I should use for mc 1.12.2?

**Comment by ProgrammerDan** [comment]
> removing orebfuscator make no longer crashes

Yes, what I'm trying to say is everyone else using orebfuscator is fine with it, no crashes. They also use many plugins.

Your situation is such that in that list of plugins, there exists another plugin (not orebfuscator), where if you kept orebfuscator and removed that _other_ plugin, you'd also no longer crash.

Trying to figure out which other plugin is interacting badly with orebfuscator is the goal of this ticket, so we can isolate what exactly is interacting badly, and determine if it's something I can change in orebfuscator, or if we'll need to recommend you reach out to the other plugin's developers.

**Comment by DahunDev** [comment]
Is there any wrong config?

ConfigVersion: 13
Booleans:
  UseCache: true
  Enabled: true
  UpdateOnDamage: true
  NoObfuscationForMetadata: true
  NoObfuscationForOps: true
  NoObfuscationForPermission: false
  LoginNotification: true
Integers:
  MaxLoadedCacheFiles: 64
  DeleteCacheFilesAfterDays: 0
  EngineMode: 2
  InitialRadius: 1
  UpdateRadius: 2
Strings:
  CacheLocation: orebfuscator_cache
  NoObfuscationForMetadataTagName: NPC
Lists:
  TransparentBlocks: []
  NonTransparentBlocks: []
Worlds:
  Default:
    Types:
    - DEFAULT
    Enabled: false
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    BypassObfuscationForSignsWithText: false
    DarknessBlocks:
    - CHEST
    - MOB_SPAWNER
    Mode1Block: STONE
    RandomBlocks: []
    ObfuscateBlocks: []
    ProximityHider:
      Enabled: true
      Distance: 16
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - ANVIL
      - BURNING_FURNACE
      - DIAMOND_ORE
      - DISPENSER
      - EMERALD_ORE
      - ENDER_CHEST
      - FURNACE
      - MOB_SPAWNER
      - TRAPPED_CHEST
      UseFastGazeCheck: true
  Normal:
    Types:
    - NORMAL
    Mode1Block: STONE
    RandomBlocks:
    - STONE
    ObfuscateBlocks:
    - CHEST
    - COAL_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - ENDER_CHEST
    - GLOWING_REDSTONE_ORE
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - REDSTONE_ORE
  TheEnd:
    Types:
    - THE_END
    Mode1Block: ENDER_STONE
    RandomBlocks:
    - BEDROCK
    - ENDER_STONE
    - END_BRICKS
    - OBSIDIAN
    - PURPUR_BLOCK
    ObfuscateBlocks:
    - ENDER_STONE
  Nether:
    Types:
    - NETHER
    Mode1Block: NETHERRACK
    RandomBlocks:
    - GRAVEL
    - NETHERRACK
    - NETHER_BRICK
    - QUARTZ_ORE
    - SOUL_SAND
    ObfuscateBlocks:
    - NETHERRACK
    - QUARTZ_ORE
  EnabledWorlds:
    Names:
    - 야생
    Enabled: true

**Comment by DahunDev** [comment]
Orebfuscator handles what?

JUST PACKET OR REAL STONES, chunks?
How that work.

**Comment by ProgrammerDan** [comment]
Orebfuscator intercepts packet sends and updates, and sends "faked" data to the player but leaves the real world alone. 

If other plugins are also updating those packets that are sent to the players, it can cause the kind of exceptions you are describing.

**Comment by DahunDev** [comment]
> If other plugins are also updating those packets that are sent to the players, it can cause the kind of exceptions you are describing.

I think, it may casues by ProtocolSupport which support minecraft from 1.5.2 to  1.12.2 And I'm changed config the support 1.8~1.12.2


But, the ProtocolSupport plugin and Anti-xray(this Orebfuscator ) is essential plugins for my server.

**Comment by ProgrammerDan** [comment]
hmm, I've used ProtocolSupport alongside Orebfuscator on 1.12 and never had any issues. I would be surprised if it was that, although can't immediately rule it out -- try removing protocolsupport briefly and seeing if the exception goes away?

**Comment by DahunDev** [comment]
> hmm, I've used ProtocolSupport alongside Orebfuscator on 1.12 and never had any issues. I would be surprised if it was that, although can't immediately rule it out -- try removing protocolsupport briefly and seeing if the exception goes away?

But, the issue is not always happen, and I've running 80 players online server.

And I also using,  ProtocolSupportLegacySupport version 1.0
 Author: _Shevchik_
 ProtocolSupportStuff version 1.0.2

**Comment by DahunDev** [comment]
And, I wonder which version is best correct for MC 1,12,2?

**Comment by ProgrammerDan** [comment]
hmm, haven't used that specific build of ProtocolSupport(s). 

From an orebfuscator perspective, you are using the correct version.

**Comment by DahunDev** [comment]
So,Which orebfuscator  version I should use for mc 1.12.2?

**Comment by ProgrammerDan** [comment]
I've answered this a number of times, you're using the best version. 

Changing versions won't help that some other plugin + orebfuscator don't play nice with each other, sorry :(

**Comment by DahunDev** [comment]
I sent the crash full log to email. 

Finding what plugins are problem is difficult because that error randomly occures, not much but more often time when more online users. 

The paperspigot's anti-x ray didn't cause the this crashes. BUT paperspigot is not compatible with variabletriggers.

**Comment by DahunDev** [comment]
In spigot site, another users have same problems

https://www.spigotmc.org/threads/rare-server-crash-occurring-log-info-included.325108/

**Comment by ProgrammerDan** [comment]
Interesting little note there about FAWE -- which you also have. If you remove FAWE, any improvement? (Fast asynchonous world editor)

**Comment by DahunDev** [comment]
No, removing FAWE was not affected any thing orebfuscator4.

Still hav the server crashes.

**Comment by DahunDev** [comment]
It was the version problems.

Version above 4.4.0 is not compatible with mc 1.12.2

I downgrade the version from 4.4.4 to Version 4.3.3, there are no longer crahses.

**Comment by ProgrammerDan** [comment]
Are you sure? Ticket opened while you were running 4.3.3 -- so returning to
that shouldn't fix the crashes.

**Comment by DahunDev** [comment]
I mistyped the version 4.4.2~4.4.4 to 4.3.3

Reason of reopening issue is version 4.3.3 has no problems but, newer version have the errors.
And closed issue can not conversation any more,so I reopen the issue for 4.4.4
So I edit the issue version from 4.3.3 to 4.4.4.

**Comment by ProgrammerDan** [comment]
Got it - thanks! Will continue to consider this an open problem, although
that adds mystery...

**Comment by DahunDev** [comment]
What's are mystery?

**Comment by ProgrammerDan** [comment]
The changes made inbetween these versions doesn't explain the problem at
first glance. Hence mystery

**Comment by sepiatonal** [comment]
I also ran into this problem today, and was also able to fix it by downgrading to 4.3.3.

**Comment by ProgrammerDan** [comment]
I'm glad reverting was able to address this for you!

**Comment by GavJenks** [comment]
One of our bungee shards crashed twice due to this suddenly, no new plugins have been added in ages there. I have neither "protocolsupport" (i do have protocollib) nor "FAWE" whatever that is. Don't see any other packet manipulator, the only one I can think of is vanishnopacket, but that was removed awhile back.

I do have 4.4.3, will try 4.3.3, but it was already only crashing every few days, so might be unclear if it was fixed for a long time.

**Comment by GavJenks** [comment]
I suppose bungee itself sends some weird packets maybe

**Comment by NgLoader** [comment]
Try this [version](https://github.com/TeamWuffy/Orebfuscator/releases)
