### ISSUE TITLE
Could not pass event BlockDamageEvent to Orebfuscator4 v4.4.3

### ISSUE THREAD

**Issue by fjeddy** [lishid/Orebfuscator#216]
This error only occurs in the nether. And whatever I do, I can't seem to disable it.

Spigot 1.13.2, vanilla generated Orebfuscator config files.

```
[14:53:28 ERROR]: Could not pass event BlockDamageEvent to Orebfuscator4 v4.4.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callBlockDamageEvent(CraftEventFactory.java:357) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:179) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1162) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
[14:53:28 ERROR]: Could not pass event BlockBreakEvent to Orebfuscator4 v4.4.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:219) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1176) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
```

**Comment by KarlOfDuty** [comment]
Pretty sure this is the same error as #210

**Comment by ProgrammerDan** [comment]
Please try https://github.com/lishid/Orebfuscator/releases/tag/4.4.4 this release and let me know if the problem is fixed.

**Comment by fjeddy** [comment]
It does indeed @ProgrammerDan, no more massive amounts of errors in the console.. Just.... Lovely. Appreciate the quick solution and response. You're the man!

**Comment by ProgrammerDan** [comment]
So glad to hear -- take care!
