### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException: 256

### ISSUE THREAD

**Issue by Blueeyestar** [lishid/Orebfuscator#217]
**_I always have errors in the console even with the latest version_**

**CraftBukkit version git-Spigot-f56e2e7-98b862a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

**Version: orebfuscator-4.4.4.jar**

[21:57:57] [Server thread/ERROR]: ChunkX = 2, chunkZ = 17
[21:57:57] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 256
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readSectionHeader(ChunkMapManager.java:369)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextSection(ChunkMapManager.java:341)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextLayer(ChunkMapManager.java:285)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readNextBlock(ChunkMapManager.java:246)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.obfuscation.Calculations.obfuscate(Calculations.java:170)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.obfuscation.Calculations.obfuscateOrUseCache(Calculations.java:69)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:87)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:193)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:157)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1391)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1364)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunk.sendChunk(SourceFile:122)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunk.a(SourceFile:63)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunkMap.addPlayer(PlayerChunkMap.java:253)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:286)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:384)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:162)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:149)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[21:57:58] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by ProgrammerDan** [comment]
~If you figured this out, can you share what the answer was?~

Nevermind, I see the new ticket

**Comment by Blueeyestar** [comment]
Unfortunately, the problem still exists

[21:54:32] [Server thread/ERROR]: ChunkX = 182, chunkZ = 174
[21:54:32] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 256
[21:54:32] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readSectionHeader(ChunkMapManager.java:369)
[21:54:32] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextSection(ChunkMapManager.java:341)
[21:54:32] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.increaseY(ChunkMapManager.java:301)
[21:54:32] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextLayer(ChunkMapManager.java:274)
[21:54:32] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.create(ChunkMapManager.java:90)
[21:54:32] [Server thread/WARN]: 	at com.lishid.orebfuscator.obfuscation.Calculations.obfuscate(Calculations.java:161)
[21:54:32] [Server thread/WARN]: 	at com.lishid.orebfuscator.obfuscation.Calculations.obfuscateOrUseCache(Calculations.java:69)
[21:54:32] [Server thread/WARN]: 	at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:87)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[21:54:32] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:193)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:157)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1391)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1364)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunk.a(SourceFile:162)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunk.d(SourceFile:186)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunkMap.flush(PlayerChunkMap.java:101)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:291)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[21:54:32] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)

**Comment by ProgrammerDan** [comment]
Apologies, I've been diverted from this for a bit. Will be a bit longer
before I personally can investigate a fix.
