### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException: 256

### ISSUE THREAD

**Issue by Blueeyestar** [lishid/Orebfuscator#218]
I always have errors in the console even with the latest version

Mc Version: CraftBukkit version git-Spigot-f56e2e7-98b862a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Version: orebfuscator-4.4.4.jar

[21:57:57] [Server thread/ERROR]: ChunkX = 2, chunkZ = 17
[21:57:57] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 256
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readSectionHeader(ChunkMapManager.java:369)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextSection(ChunkMapManager.java:341)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextLayer(ChunkMapManager.java:285)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readNextBlock(ChunkMapManager.java:246)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.obfuscation.Calculations.obfuscate(Calculations.java:170)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.obfuscation.Calculations.obfuscateOrUseCache(Calculations.java:69)
[21:57:58] [Server thread/WARN]: 	at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:87)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[21:57:58] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:193)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:157)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1391)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1364)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunk.sendChunk(SourceFile:122)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunk.a(SourceFile:63)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunkMap.addPlayer(PlayerChunkMap.java:253)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:286)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:384)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:162)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:149)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[21:57:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[21:57:58] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by ProgrammerDan** [comment]
This looks identical to https://github.com/lishid/Orebfuscator/issues/204 which I was never able to duplicate. 


I'll attempt to dig into this. I know Aleksey had said he had some ideas, but has since ghosted.

**Comment by Blueeyestar** [comment]
Thank you for taking care of that. I wish you a nice Weekend

**Comment by Blueeyestar** [comment]
The problem is still present after 4 months. Is there any progress yet?


[11:23:20] [Server thread/ERROR]: ChunkX = -204, chunkZ = -66
[11:23:20] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 256
[11:23:20] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readSectionHeader(ChunkMapManager.java:369)
[11:23:20] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextSection(ChunkMapManager.java:341)
[11:23:20] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextLayer(ChunkMapManager.java:285)
[11:23:20] [Server thread/WARN]: 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readNextBlock(ChunkMapManager.java:246)
[11:23:20] [Server thread/WARN]: 	at com.lishid.orebfuscator.obfuscation.Calculations.obfuscate(Calculations.java:170)
[11:23:20] [Server thread/WARN]: 	at com.lishid.orebfuscator.obfuscation.Calculations.obfuscateOrUseCache(Calculations.java:69)
[11:23:20] [Server thread/WARN]: 	at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:87)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[11:23:20] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:193)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:157)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1375)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1348)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunk.a(SourceFile:162)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunk.d(SourceFile:186)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunkMap.flush(PlayerChunkMap.java:101)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:291)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[11:23:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[11:23:20] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by ProgrammerDan** [comment]
I had long hoped that Aleksey would return, as when last I spoke he
indicated he had a fix in mind. He has not, and I've been super busy. As
always, I'll merge in any credible PR to fix, barring that a fix is
dependent on my availability, which is constrained right now. I sincerely
apologize for this incredibly long delay, your patience is super-human.

**Comment by Chevels** [comment]
I've this issue too, and it spam my logs for months...

**Here is the error log:**
[21:14:45 ERROR]: ChunkX = -64, chunkZ = 190
[21:14:45 WARN]: java.lang.ArrayIndexOutOfBoundsException: 256
[21:14:45 WARN]: at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readSectionHeader(ChunkMapManager.java:369)
[21:14:45 WARN]: at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextSection(ChunkMapManager.java:341)
[21:14:45 WARN]: at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextLayer(ChunkMapManager.java:285)
[21:14:45 WARN]: at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readNextBlock(ChunkMapManager.java:246)
[21:14:45 WARN]: at com.lishid.orebfuscator.obfuscation.Calculations.obfuscate(Calculations.java:170)
[21:14:45 WARN]: at com.lishid.orebfuscator.obfuscation.Calculations.obfuscateOrUseCache(Calculations.java:69)
[21:14:45 WARN]: at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:87)
[21:14:45 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[21:14:45 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[21:14:45 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[21:14:45 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[21:14:45 WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[21:14:45 WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[21:14:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[21:14:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[21:14:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[21:14:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[21:14:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[21:14:45 WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:194)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:158)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1398)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1371)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.PlayerChunk.sendChunk(PlayerChunk.java:121)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.PlayerChunk.a(PlayerChunk.java:63)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.PlayerCh
unkMap.movePlayer(PlayerChunkMap.java:335)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.PlayerList.updateChunks(PlayerList.java:392)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:979)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[21:14:45 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:14:45 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[21:14:45 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[21:14:45 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:15:06 ERROR]: ChunkX = -64, chunkZ = 190
[21:15:06 WARN]: java.lang.ArrayIndexOutOfBoundsException

**Comment by NgLoader** [comment]
https://github.com/lishid/Orebfuscator/pull/236
