### ISSUE TITLE
THE BİG REPORT!

### ISSUE THREAD

**Issue by successed** [lishid/Orebfuscator#219]
[20:51:55 ERROR]: Could not pass event BlockBreakEvent to Orebfuscator4 v4.4.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-498]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:84) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.EntityPlayer.tick(EntityPlayer.java:339) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1549) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1516) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:621) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1289) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:598) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1099) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-498]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at com.lishid.orebfuscator.obfuscation.BlockUpdate.update(BlockUpdate.java:69) ~[?:?]
        at com.lishid.orebfuscator.obfuscation.BlockUpdate.update(BlockUpdate.java:49) ~[?:?]
        at com.lishid.orebfuscator.listeners.OrebfuscatorBlockListener.onBlockBreak(OrebfuscatorBlockListener.java:38) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor17.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-498]
        ... 16 more

**Comment by ProgrammerDan** [comment]
Please update to the v4.4.4 in the releases section. I haven't done a full
release on Spigot.org yet -- need to get that up there. It will fix this
specific problem for you.

Please note however that since you are using Paper, there is an extra step.
Check the release notes of v4.4.4 for how to disable asynchronous chunk
loading, which is at present incompatible with Orebfuscator.

**Comment by successed** [comment]
give me download url please

**Comment by ProgrammerDan** [comment]
You are on the "issues" tab. Find right next to it the "releases" tab.
Click it, then pick the first entry in the page that displays -- that will
be 4.4.4.

**Comment by ProgrammerDan** [comment]
https://github.com/lishid/Orebfuscator/releases/tag/4.4.4

not sure if you found it yet, here it is.
