### ISSUE TITLE
Unhandled Exception number 2048 onPacketSending(PacketEvent) on v4.4.4

### ISSUE THREAD

**Issue by iViscosity** [lishid/Orebfuscator#226]
Don't know how similar this is to any other issue, but I couldn't find one with this error.

Full error:
```[00:55:02] [Server thread/ERROR]: [Orebfuscator4] Unhandled exception number 2048 occured in onPacketSending(PacketEvent) for Orebfuscator4
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.WorldServer.getChunkProvider()Lnet/minecraft/server/v1_13_R2/ChunkProviderServer;
	at com.lishid.orebfuscator.nms.v1_13_R2.NmsManager.getBlockData(NmsManager.java:542) ~[?:?]
	at com.lishid.orebfuscator.nms.v1_13_R2.NmsManager.loadChunkAndGetBlockId(NmsManager.java:473) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.Calculations.areAjacentBlocksTransparent(Calculations.java:400) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.Calculations.areAjacentBlocksTransparent(Calculations.java:418) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.Calculations.obfuscate(Calculations.java:199) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.Calculations.obfuscateOrUseCache(Calculations.java:69) ~[?:?]
	at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:87) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:194) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:158) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1398) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1371) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.PlayerChunk.sendChunk(PlayerChunk.java:121) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.PlayerChunk.a(PlayerChunk.java:63) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.PlayerChunkMap.movePlayer(PlayerChunkMap.java:335) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.PlayerList.updateChunks(PlayerList.java:392) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:465) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.PacketPlayInTeleportAccept.a(SourceFile:31) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.PacketPlayInTeleportAccept.a(SourceFile:8) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-947a8e7-17ff1e0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

I noticed this error occurs when someone very quickly changes position (I had 2 players on my server teleport to the other and immediately following it showed this error).

It doesn't seem to break anything, but it could have some underlying problems I'm not aware of. 

Only posting here because orebfuscator shows up near the top, so it may or may not even be related :)

Also as a side note: I am receiving the "Could not pass event BlockDamageEvent to Orebfuscator4 v4.4.4" as many others are referencing. I do have a slightly outdated version of Spigot and will be updating tomorrow, so I'll come back with results then. It may be that that is causing this issue! :)

**Comment by ProgrammerDan** [comment]
Thank you for reporting!
