### ISSUE TITLE
When entering the nether BIG lag spike.

### ISSUE THREAD

**Issue by thierrybla** [lishid/Orebfuscator#228]
With the newest spigot versison, ProtocolLib version and Orebfuscator version when you enter the nether it will lag for a solid 5-10 seconds.

When rolling back to 4.4.2 of Orebfuscator this issue is gone.

Please let me know if this only happens to me.

**Comment by Chevels** [comment]
Same for me. When this lag happen, my logs have a very huge spam with the error below.
In fact this error repeats itself indefinitely as long as the player stays in the Nether.
According to my tests, it looks like this error occurs when a player goes into the Nether with the mod X-Ray enabled. I can not say completely because I could not do any additional tests but it's a track to check.

### error log:
[18:18:37 ERROR]: Could not pass event BlockDamageEvent to Orebfuscator4 v4.4.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callBlockDamageEvent(CraftEventFactory.java:334) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:179) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1169) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at com.lishid.orebfuscator.obfuscation.BlockUpdate.update(BlockUpdate.java:69) ~[?:?]
at com.lishid.orebfuscator.obfuscation.BlockUpdate.update(BlockUpdate.java:49) ~[?:?]
at com.lishid.orebfuscator.listeners.OrebfuscatorBlockListener.onBlockDamage(OrebfuscatorBlockListener.java:56) ~[?:?]
at sun.reflect.GeneratedMethodAccessor370.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorIm
pl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[gbinvl_spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
... 17 more

**Comment by thierrybla** [comment]
Hey, I noticed paper spigot does not have this problem. just to add.
