### ISSUE TITLE
java.lang.IllegalArgumentException: Block 1126 is absent in output palette

### ISSUE THREAD

**Issue by Chevels** [lishid/Orebfuscator#229]
Hello,
Since I used Orebfuscator 4.4.3 on a Spigot 1.13.2 server I've this error who spam a lot my log:

[21:12:24 ERROR]: ChunkX = -64, chunkZ = 190
[21:12:24 WARN]: java.lang.IllegalArgumentException: Block 1126 is absent in output palette.
[21:12:24 WARN]: at com.lishid.orebfuscator.chunkmap.ChunkMapManager.writeOutputBlock(ChunkMapManager.java:187)
[21:12:24 WARN]: at com.lishid.orebfuscator.obfuscation.Calculations.obfuscate(Calculations.java:273)
[21:12:24 WARN]: at com.lishid.orebfuscator.obfuscation.Calculations.obfuscateOrUseCache(Calculations.java:69)
[21:12:24 WARN]: at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:87)
[21:12:24 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[21:12:24 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[21:12:24 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[21:12:24 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[21:12:24 WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[21:12:24 WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[21:12:24 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[21:12:24 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[21:12:24 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[21:12:24 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[21:12:24 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[21:12:24 WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:194)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:158)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1398)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1371)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.PlayerChunk.sendChunk(PlayerChunk.java:121)
[21:12:24 WARN]: at net.mine
craft.server.v1_13_R2.PlayerChunk.a(PlayerChunk.java:63)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.PlayerChunkMap.movePlayer(PlayerChunkMap.java:335)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.PlayerList.updateChunks(PlayerList.java:392)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:465)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInTeleportAccept.a(SourceFile:31)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInTeleportAccept.a(SourceFile:8)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[21:12:24 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:12:24 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[21:12:24 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[21:12:24 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by ProgrammerDan** [comment]
Yes, known problem but unknown (as of yet) solution. Sorry for this, hoped
that the main dev would return and fix but he does not appear to have
returned. I haven't had time yet to work on it, my apologies.

**Comment by Cyclopeanserver** [comment]
I know this is old, but... I've only gotten this error today. I've run the latest 4.4.7 without permission bypass and never had that problem. Today, the only player with permission bypass was playing, and the error below is from the chunk they were building in.

01.05 02:05:19 [Server] ERROR [Minecraft.OFC] ChunkX = 1033, chunkZ = 16
01.05 02:05:19 [Server] WARN java.lang.IllegalArgumentException: Block 9130 is absent in output palette.
01.05 02:05:19 [Server] WARN at com.lishid.orebfuscator.chunkmap.ChunkMap.writeOutputBlock(ChunkMap.java:148)
01.05 02:05:19 [Server] WARN at com.lishid.orebfuscator.obfuscation.Calculations.obfuscate(Calculations.java:268)
01.05 02:05:19 [Server] WARN at com.lishid.orebfuscator.obfuscation.Calculations.obfuscateOrUseCache(Calculations.java:76)
01.05 02:05:19 [Server] WARN at com.lishid.orebfuscator.hook.ProtocolLibHandler$1.onPacketSending(ProtocolLibHandler.java:134)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
01.05 02:05:19 [Server] WARN at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:200)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:169)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1558)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1531)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.EntityPlayer.a(EntityPlayer.java:1778)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1713)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:1170)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1531)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:935)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1157)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1208)
01.05 02:05:19 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
01.05 02:05:19 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by Chevels** [comment]
Unfortunately this plugin was totaly abandoned...
In addition it is so buggy that I had to remove it from my server. Apparently no developer understands the problem and does not know how to solve it since MC 1.13.2 :/

**Comment by NgLoader** [comment]
@Chevels the error is already fixed in the new version

**Comment by NgLoader** [comment]
@ProgrammerDan look at the frok from Imprex-Development

**Comment by Chevels** [comment]
@NgLoader Thank you but even with your fork the bug is still present but you tell me that you can't reproduce it... Sometimes entire chunk is full of TNT block for clients and my console is spammed by lot of error when this happen :/

**Comment by NgLoader** [comment]
@Chevels thats not the newest Version, I mean the Imprex-Development version but this is work in progress

**Comment by Chevels** [comment]
@NgLoader It seems we have to build the Imprex-Development version to use it, and for years I can't install the software needed for that on my computer :/ I don't know why exactly, a dependencie issue I guess.
I've to wait for a dev build or a release to test it. If a usable build is available, I did not find it.

Thank you for your reply :)

**Comment by NgLoader** [comment]
https://github.com/Imprex-Development/Orebfuscator/actions/runs/93182727
