### ISSUE TITLE
Could not pass event BlockPistonExtendEvent to Orebfuscator4 v4.4.3

### ISSUE THREAD

**Issue by Ayymoss** [lishid/Orebfuscator#231]
```
[21:10:32] [Server thread/ERROR]: Could not pass event BlockPistonExtendEvent to Orebfuscator4 v4.4.3
java.lang.NullPointerException: null
	at com.lishid.orebfuscator.obfuscation.BlockUpdate.update(BlockUpdate.java:69) ~[?:?]
	at com.lishid.orebfuscator.listeners.OrebfuscatorBlockListener.onBlockPistonExtend(OrebfuscatorBlockListener.java:76) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor32.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-626]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-626]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-626]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.BlockPiston.a(BlockPiston.java:332) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.BlockPiston.a(BlockPiston.java:188) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.IBlockData.a(IBlockData.java:204) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:1138) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.WorldServer.an(WorldServer.java:1127) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:318) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1091) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-626]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
[21:10:32] [Server thread/ERROR]: Could not pass event BlockPistonExtendEvent to Orebfuscator4 v4.4.3
java.lang.NullPointerException: null

```

Log is spammed with this...

**Comment by Ayymoss** [comment]
So many of these errors...

```
[21:53:54] [Server thread/ERROR]: Could not pass event BlockDamageEvent to Orebfuscator4 v4.4.3
java.lang.NullPointerException: null
	at com.lishid.orebfuscator.obfuscation.BlockUpdate.update(BlockUpdate.java:69) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.BlockUpdate.update(BlockUpdate.java:49) ~[?:?]
	at com.lishid.orebfuscator.listeners.OrebfuscatorBlockListener.onBlockDamage(OrebfuscatorBlockListener.java:56) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-626]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-626]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-626]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-626]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callBlockDamageEvent(CraftEventFactory.java:378) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:184) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1271) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-626]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-626]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-626]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

**Comment by ProgrammerDan** [comment]
Thanks for the report.

**Comment by witangz** [comment]
I have met the same question. It nearly report "[ERROR]: Could not pass event BlockPistonExtendEvent to Orebfuscator4 v4.4.3" every second. I wonder if it can work correctly with working pistons.
Please tell me if you solve this problem.

**Comment by NgLoader** [comment]
Try this [Releases](https://github.com/TeamWuffy/Orebfuscator/releases)
