### ISSUE TITLE
Problem with material reader

### ISSUE THREAD

**Issue by belfedia** [lishid/Orebfuscator#245]
I use paperspigot 1.15.1 #34 

> 2020-01-07 20:31:23 [ERROR] Error occurred while enabling Orebfuscator4 v4.4.6 (Is it up to date?)
java.lang.NullPointerException: null
	at com.lishid.orebfuscator.config.MaterialReader.getMaterialIdByPath(MaterialReader.java:60) ~[?:?]
	at com.lishid.orebfuscator.config.WorldReader.readWorld(WorldReader.java:183) ~[?:?]
	at com.lishid.orebfuscator.config.WorldReader.readWorldByType(WorldReader.java:90) ~[?:?]
	at com.lishid.orebfuscator.config.WorldReader.load(WorldReader.java:48) ~[?:?]
	at com.lishid.orebfuscator.config.ConfigManager.load(ConfigManager.java:124) ~[?:?]
	at com.lishid.orebfuscator.Orebfuscator.loadOrebfuscatorConfig(Orebfuscator.java:117) ~[?:?]
	at com.lishid.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:68) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-32]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-32]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-32]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-32]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-32]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:227) ~[patched_1.15.1.jar:git-Paper-32]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-32]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2020-01-07 20:31:23 [INFO] Disabling Orebfuscator4 v4.4.6

**Comment by belfedia** [comment]
No more, it was a config problem, plugin don't upgrade config.yml
with clean config.yml that work :)

**Comment by ProgrammerDan** [comment]
Was going to suggest that as cause :)

**Comment by NgLoader** [comment]
We currently remaking Orebfuscator you can try this version
[TeamWuffy](https://github.com/TeamWuffy/Orebfuscator/releases)
or follow this repository to see the current progress
[Imprex Orebfuscator Repo](https://github.com/Imprex-Development/Orebfuscator)
