### ISSUE TITLE
CrashServer in some minutes :c (BUG) 1.12.2 - Spigot Final Build

### ISSUE THREAD

**Issue by colo13verdadeo** [lishid/Orebfuscator#246]
My server crash in some minutes when i has pasted plugin, frist time nothing, bug, in 2hours, crash:
Crashreport:
https://pastebin.com/zji09FaK
When deleted plugin, never crash.

AVG Users: 55 users.

PD: Anteriormente intente meter paper. Despues de eso empezo a crashear (support paper?).

Orebf version: 4.4.3

**Comment by NgLoader** [comment]
We are working on a new version where this bug will be fixed.

**Comment by NgLoader** [comment]
Please use the paper anti-xray system first until we release the new version.
Sry for the inconvenience

Or try this version first [here](https://github.com/TeamWuffy/Orebfuscator/releases)

**Comment by colo13verdadeo** [comment]
I found error:
Caused by i will add iron ore + coal ore + restone ore + motor 1.

And...
Possibly error lag:
02.04 03:54:30 [Server] WARN java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
02.04 03:54:30 [Server] WARN at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
02.04 03:54:30 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
02.04 03:54:30 [Server] WARN at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:170)
02.04 03:54:30 [Server] WARN at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:153)
02.04 03:54:30 [Server] WARN at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
02.04 03:54:30 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:181)
02.04 03:54:30 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:630)
02.04 03:54:30 [Server] WARN at org.bukkit.Location.getChunk(Location.java:91)
02.04 03:54:30 [Server] WARN at com.songoda.ultimatekits.handlers.DisplayItemHandler.displayItem(DisplayItemHandler.java:51)
02.04 03:54:30 [Server] WARN at com.songoda.ultimatekits.handlers.DisplayItemHandler.displayItems(DisplayItemHandler.java:37)
02.04 03:54:30 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
02.04 03:54:30 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
02.04 03:54:30 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
02.04 03:54:30 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02.04 03:54:30 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02.04 03:54:30 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by colo13verdadeo** [comment]
4.4.3 no support 1.12.2
=C

**Comment by NgLoader** [comment]
Try 4.4.7

**Comment by NgLoader** [comment]
Whats is **motor 1**?

**Comment by colo13verdadeo** [comment]
motor 1= engine 1

> Whats is **motor 1**?

**Comment by colo13verdadeo** [comment]
> Try 4.4.7

This nos support 1.12.2. 
i wrote it wrong.

**Comment by NgLoader** [comment]
Hm, okay thats bad

The new version supports 1.9 - 1.15.2

**Comment by colo13verdadeo** [comment]
But, my server is paper 1.12.2 last build, and he cant load plugin.

**Comment by NgLoader** [comment]
Your using the latest protocollib version?

**Comment by colo13verdadeo** [comment]
how i can view Version?

**Comment by hamza-cskn** [comment]
@colo13verdadeo you must use /ver protocollib
also, i think i got same error. and i using 1.12.2 too.

**Comment by 0ct0ber** [comment]
I've had the same error. Fresh installation of Spigot 1.12.2, latest version of ProtocolLib and Orebfuscator, and no other plugins, and the server crashed with this message. I'm not sure if this is a repeating error or a one-time thing, but this occurred shortly after configuring and then doing a restart.

Crash log: https://pastebin.com/8vqh3U2x

Configuration file: https://pastebin.com/NbhNPUVN

**Comment by NgLoader** [comment]
Give this version a try: https://github.com/Imprex-Development/Orebfuscator/releases/latest
