### ISSUE TITLE
Feature request: Option to not check for updates

### ISSUE THREAD

**Issue by SlimeDog** [lishid/Orebfuscator#255]
Orebfuscator-5.1.3

We block (nearly) all outgoing network connections (Spigot plugins are required to work without network connections). On start-up
```
[20:07:19] [Server thread/INFO]: [Orebfuscator] Enabling Orebfuscator v5.1.3
[20:07:19] [Server thread/INFO]: [Orebfuscator] Using '/home/ram/Spigot/UNIVERSE/orebfuscator_cache' as chunk cache path
[20:07:19] [Server thread/INFO]: [Orebfuscator] cache.protocolLibThreads is less than one, choosing processor count as value = 8
[20:07:19] [Server thread/INFO]: [Orebfuscator] Searching NMS adapter for server version "v1_16_R3"!
[20:07:19] [Server thread/INFO]: [Orebfuscator] NMS adapter for server version "v1_16_R3" found!
[20:07:19] [Server thread/WARN]: [Orebfuscator] Unable to fetch latest update from: https://api.github.com/repos/Imprex-Development/Orebfuscator/releases/latest
java.io.IOException: Connect failed
        at me.lucko.networkinterceptor.interceptors.ProxySelectorInterceptor$LoggingSelector.select(ProxySelectorInterceptor.java:59) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1071) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1069) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1068) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1512) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1510) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) ~[?:?]
        at net.imprex.orebfuscator.UpdateSystem.getReleaseData(UpdateSystem.java:44) ~[?:?]
        at net.imprex.orebfuscator.UpdateSystem.getTagName(UpdateSystem.java:56) ~[?:?]
        at net.imprex.orebfuscator.UpdateSystem.isUpdateAvailable(UpdateSystem.java:73) ~[?:?]
        at net.imprex.orebfuscator.UpdateSystem.checkForUpdates(UpdateSystem.java:77) ~[?:?]
        at net.imprex.orebfuscator.UpdateSystem.<init>(UpdateSystem.java:35) ~[?:?]
        at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[20:07:19] [Server thread/ERROR]: [Orebfuscator] An error occurred while enabling plugin
[20:07:19] [Server thread/ERROR]: [Orebfuscator] null
java.lang.NullPointerException: null
        at net.imprex.orebfuscator.UpdateSystem.getTagName(UpdateSystem.java:57) ~[?:?]
        at net.imprex.orebfuscator.UpdateSystem.isUpdateAvailable(UpdateSystem.java:73) ~[?:?]
        at net.imprex.orebfuscator.UpdateSystem.checkForUpdates(UpdateSystem.java:77) ~[?:?]
        at net.imprex.orebfuscator.UpdateSystem.<init>(UpdateSystem.java:35) ~[?:?]
        at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[20:07:19] [Server thread/INFO]: [Orebfuscator] Disabling Orebfuscator v5.1.3
[20:07:19] [Server thread/ERROR]: Error occurred while disabling Orebfuscator v5.1.3 (Is it up to date?)
java.lang.NullPointerException: null
        at net.imprex.orebfuscator.Orebfuscator.onDisable(Orebfuscator.java:84) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.imprex.orebfuscator.Orebfuscator.onEnableFailed(Orebfuscator.java:104) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:358) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar-2021-01-08-1953:git-Spigot-a56d446-7029c0a]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by NgLoader** [comment]
You can disable the update check in the config
(Read the wiki)

**Comment by NgLoader** [comment]
And this is the false repo, pls report bugs to Imprex-Development

**Comment by SlimeDog** [comment]
Apologies. See [Dev issue #89](https://github.com/Imprex-Development/Orebfuscator/issues/89).
