### ISSUE TITLE
Unhandled exception under number 128

### ISSUE THREAD

**Issue by BetterGarlic381** [lishid/Orebfuscator#268]
Hey, I've had the plugin installed for a while and I've only just recently started getting this error

- [Sat 09:00:06 ERROR Minecraft] [Orebfuscator] Unhandled exception number 128 occured in onAsyncPacket() for Orebfuscator
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.hasPermission(String)" because "player" is null
    at net.imprex.orebfuscator.util.PermissionUtil.canDeobfuscate(PermissionUtil.java:9)
    at net.imprex.orebfuscator.obfuscation.ObfuscationListener.shouldNotObfuscate(ObfuscationListener.java:72)
    at net.imprex.orebfuscator.obfuscation.ObfuscationListener.onPacketSending(ObfuscationListener.java:45)
    at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:640)
    at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:596)
    at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48)
    at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229)
    at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300)
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82)
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by NgLoader** [comment]
Please report this issue to [Imprex-Development](https://github.com/Imprex-Development/Orebfuscator/issues)
