### ISSUE TITLE
Version 3.0.0 Errors

### ISSUE THREAD

**Issue by Aggroblut** [lishid/Orebfuscator#42]
Orebfuscator 3.0.0
Spigot: latest Version atm
```
[21:47:45 ERROR]: Could not pass event BlockPistonExtendEvent to Orebfuscator3 v
3.0.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:305) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at net.minecraft.server.v1_8_R1.BlockPiston.a(BlockPiston.java:335) [spi
got-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at net.minecraft.server.v1_8_R1.BlockPiston.a(BlockPiston.java:169) [spi
got-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at net.minecraft.server.v1_8_R1.WorldServer.a(WorldServer.java:1074) [sp
igot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at net.minecraft.server.v1_8_R1.WorldServer.ak(WorldServer.java:1060) [s
pigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at net.minecraft.server.v1_8_R1.WorldServer.doTick(WorldServer.java:257)
 [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:7
41) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:3
16) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:6
23) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:526) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -104
        at com.lishid.orebfuscator.OrebfuscatorConfig.isObfuscated(OrebfuscatorC
onfig.java:140) ~[?:?]
        at com.lishid.orebfuscator.obfuscation.BlockUpdate.AddBlockCheck(BlockUp
date.java:85) ~[?:?]
        at com.lishid.orebfuscator.obfuscation.BlockUpdate.GetAjacentBlocks(Bloc
kUpdate.java:69) ~[?:?]
        at com.lishid.orebfuscator.obfuscation.BlockUpdate.Update(BlockUpdate.ja
va:38) ~[?:?]
        at com.lishid.orebfuscator.listeners.OrebfuscatorBlockListener.onBlockPi
stonExtend(OrebfuscatorBlockListener.java:83) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:301) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
        ... 13 more
```

Also Engine-Mode 2 not working, looking screen:
![enginemode2_not_working](https://cloud.githubusercontent.com/assets/5066584/5619886/71b89fbc-9526-11e4-9cef-f5b97e0f384a.png)

**Comment by Bobcat00** [comment]
I'm also seeing the BlockPistonExtendEvent exception with CraftBukkit version git-Bukkit-96d09e3.

**Comment by lishid** [comment]
Could you guys let me know if this fixes the issues?

http://dev.bukkit.org/bukkit-plugins/orebfuscator/files/140-orebfuscator-3-0-1/

**Comment by MarioG1** [comment]
Engine-Mode 1 is also not working.

**Comment by Aggroblut** [comment]
Hey lishid,

now the BlockPistonExtendEvent Error is done for me but if I mine a Silverfishstone there is a error:

```
[12:56:45] [Netty Server IO #2/ERROR]: [Orebfuscator3] Unhandled exception number 64 occured in onPacketReceiving(PacketEvent) for Orebfuscator3
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 4, Size: 0)
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:193) ~[ProtocolLib.jar:?]
	at com.lishid.orebfuscator.hook.ProtocolLibHook$2.onPacketReceiving(ProtocolLibHook.java:53) ~[Orebfuscator.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:639) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:606) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:300) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:266) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:513) [ProtocolLib.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:241) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:246) [ProtocolLib.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-e497721-96d09e3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
```
_____________________

And if I install an simple xray mod and have latest protocollib build with Orebfuscator 3.0.1 I see this:
![2015-01-06_13 03 06](https://cloud.githubusercontent.com/assets/5066584/5628253/ef4b4668-95a4-11e4-8047-a80316278343.png)


Thanks for all of your work lishid!

**Comment by lishid** [comment]
Released a new version. Please let me know if it's fixed.

**Comment by Aggroblut** [comment]
Hey lishid, 
the error with the silverfish blocks is done and the faked ores are also created. Nice work.

But there is a extreme blocklag after 8 blocks. Just build 20 stone up in the air and mine downward. After 8 I cant break the blocks. I only installed Orebfuscator v3.0.2 and ProtocolLib v3.6.3-SNAPSHOT. Using atm latest version of 1.8.  Xray in spigot.yml disabled.

**Comment by lishid** [comment]
What happens once you log out and back in? 8 sounds fishy.

**Comment by Aggroblut** [comment]
When I relog I can break antoher 8 Blocks until the "lagblock" comes. The "lagblock" is a invisible block, which is like a barrier I cant walk over them. I can see him when I relog or right click on this block. But I can only break after relog. I tested this with stone, sand and dirt. All the same.

**Comment by lishid** [comment]
This has been reported to me as an issue with my ProtocolLib Hook layer. Please confirm if you can that this doesn't occur without PL. I will get on fixing it as soon as I get time later today or tomorrow. Thanks!

**Comment by Aggroblut** [comment]
Confirmed. Without ProtocolLib there isn't any "lagblock".

**Comment by lishid** [comment]
Latest version should have fixed it.

**Comment by Aggroblut** [comment]
Thanks so much! I'm happy to able to use this instead of the spigot inbuilt version. Though the cache is much efficiency and more lightweight. 
Btw could you please release your awesome plugins also on the Spigot Resources?
