### ISSUE TITLE
BlockBreakEvent exception

### ISSUE THREAD

**Issue by Bobcat00** [lishid/Orebfuscator#43]
I get the following exception when breaking a block with OFC 3.0.0 and CraftBukkit version git-Bukkit-96d09e3.

```
2015-01-05 16:32:30 [ERROR] Could not pass event BlockBreakEvent to Orebfuscator3 v3.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit.jar:git-Bukkit-96d09e3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-96d09e3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-96d09e3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-96d09e3]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:285) [craftbukkit.jar:git-Bukkit-96d09e3]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.a(PlayerInteractManager.java:121) [craftbukkit.jar:git-Bukkit-96d09e3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:573) [craftbukkit.jar:git-Bukkit-96d09e3]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:40) [craftbukkit.jar:git-Bukkit-96d09e3]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:10) [craftbukkit.jar:git-Bukkit-96d09e3]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-96d09e3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:643) [craftbukkit.jar:git-Bukkit-96d09e3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit.jar:git-Bukkit-96d09e3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit.jar:git-Bukkit-96d09e3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit.jar:git-Bukkit-96d09e3]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -97
	at com.lishid.orebfuscator.OrebfuscatorConfig.isObfuscated(OrebfuscatorConfig.java:140) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.BlockUpdate.AddBlockCheck(BlockUpdate.java:85) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.BlockUpdate.GetAjacentBlocks(BlockUpdate.java:69) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.BlockUpdate.Update(BlockUpdate.java:38) ~[?:?]
	at com.lishid.orebfuscator.listeners.OrebfuscatorBlockListener.onBlockBreak(OrebfuscatorBlockListener.java:38) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit.jar:git-Bukkit-96d09e3]
	... 16 more
```

**Comment by lishid** [comment]
Looking into it.

**Comment by lishid** [comment]
Released a new version. Please let me know if it's fixed.
