### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by drjawa** [lishid/Orebfuscator#51]
Using the latest version of spigot 1.8.3 and protocolib along with latest available orebfuscator.

Java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_45-internal]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:61) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_8_R2.ShapedRecipes.a(ShapedRecipes.java:150) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.CraftingManager.craft(CraftingManager.java:297) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.ContainerPlayer.a(ContainerPlayer.java:67) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.InventoryCrafting.setItem(InventoryCrafting.java:129) ~[spigot.jar:git-Spigot-1d14d5f-7722428]        at net.minecraft.server.v1_8_R2.Slot.set(Slot.java:55) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.Container.clickItem(Container.java:285) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1625) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInWindowClick.a(SourceFile:31) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInWindowClick.a(SourceFile:9) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45-internal]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 5 more

**Comment by suirad** [comment]
Im not seeing which file had the error, is there more to that stack trace?

**Comment by drjawa** [comment]
I don't think so, but I could try and dig something up. I can renable the plugin on civtest and I'm sure it will come up again.

**Comment by suirad** [comment]
Yea, what i usually look for is one of those lines saying what file is the issue plus the line number(disregard most of the bukkit other stuff)

**Comment by ProgrammerDan** [comment]
I'm a bit unclear how this is orebfuscator related.
