### ISSUE TITLE
NoClassDefFoundError in 1.8.6

### ISSUE THREAD

**Issue by BakaSoniji** [lishid/Orebfuscator#53]
I am using git-Spigot-044d928-e8c6403 and got following errors.
>Error occurred while enabling Orebfuscator3 v3.0.5 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/Block
        at com.lishid.orebfuscator.internal.MinecraftInternals.isBlockTransparent(MinecraftInternals.java:30) ~[?:?]
        at com.lishid.orebfuscator.OrebfuscatorConfig.generateTransparentBlocks(OrebfuscatorConfig.java:120) ~[?:?]
        at com.lishid.orebfuscator.OrebfuscatorConfig.isBlockTransparent(OrebfuscatorConfig.java:105) ~[?:?]
        at com.lishid.orebfuscator.OrebfuscatorConfig.setBlockValues(OrebfuscatorConfig.java:338) ~[?:?]
        at com.lishid.orebfuscator.OrebfuscatorConfig.load(OrebfuscatorConfig.java:411) ~[?:?]
        at com.lishid.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:57) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_11]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.Block
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.6.jar:git-Spigot-044d928-e8c6403]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_11]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_11]
        ... 14 more

**Comment by ProgrammerDan** [comment]
Are you still experiencing this issue? MarioG's latest pull should address it for you, if you are.

**Comment by ProgrammerDan** [comment]
If you're still running 1.8.6, please use this release version: https://github.com/lishid/Orebfuscator/releases/tag/v3.0.6-R3-legacy
