### ISSUE TITLE
Not compatable with Cauldron or kCauldron

### ISSUE THREAD

**Issue by tenten8401** [lishid/Orebfuscator#55]
Giving a java.lang.NoSuchFieldException: chunkCoordIntPairQueue error when any players join. a fix for this would be HIGHLY appreciated.

**Comment by ProgrammerDan** [comment]
Is this still occurring?

**Comment by Aleksey-Terzi** [comment]
Since no confirmation about problem - I'm closing issue.

**Comment by paipai1997** [comment]
The problem still exist in OFC2.1x for 1.7.10 with kCauldron.

> [18:47:30 ERROR]: [OFC] java.lang.NoSuchFieldException: chunkCoordIntPairQueue
[18:47:30 WARN]: java.lang.NoSuchFieldException: chunkCoordIntPairQueue
[18:47:30 WARN]:        at java.lang.Class.getDeclaredField(Unknown Source)
[18:47:30 WARN]:        at com.lishid.orebfuscator.utils.ReflectionHelper.setPrivateFinal(ReflectionHelper.java:58)
[18:47:30 WARN]:        at com.lishid.orebfuscator.internal.v1_7_R4.PlayerHook.HookChunkQueue(PlayerHook.java:125)
[18:47:30 WARN]:        at com.lishid.orebfuscator.hook.OrebfuscatorPlayerHook.onPlayerJoin(OrebfuscatorPlayerHook.java:45)
[18:47:30 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:47:30 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:47:30 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:47:30 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[18:47:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[18:47:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:47:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[18:47:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[18:47:30 WARN]:        at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:360)
[18:47:30 WARN]:        at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:216)
[18:47:30 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190)
[18:47:30 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465)
[18:47:30 WARN]:        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21)
[18:47:30 WARN]:        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[18:47:30 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[18:47:30 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[18:47:30 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[18:47:30 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[18:47:30 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[18:47:30 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[18:47:30 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[18:47:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[18:47:30 WARN]:        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[18:47:30 WARN]:        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[18:47:30 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[18:47:30 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[18:47:30 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
[18:47:30 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
[18:47:30 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[18:47:30 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[18:47:30 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by ProgrammerDan** [comment]
I apologize but we are not offering any support for pre-minecraft 1.9 Orebfuscator.
