### ISSUE TITLE
ArrayIndexOutOfBounds Exception in initOutputPalette

### ISSUE THREAD

**Issue by RoboMWM** [lishid/Orebfuscator#79]
This happened when someone joined the server. Not sure of any other conditions other than the location, which is in a sea temple.

```
2016-04-26 19:09:08 [Server thread/WARN] java.lang.ArrayIndexOutOfBoundsException: -128
2016-04-26 19:09:08 [Server thread/WARN] 	at com.lishid.orebfuscator.chunkmap.ChunkMapManager.initOutputPalette(ChunkMapManager.java:116)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.lishid.orebfuscator.obfuscation.Calculations.Obfuscate(Calculations.java:256)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.lishid.orebfuscator.obfuscation.Calculations.ObfuscateOrUseCache(Calculations.java:96)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:63)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:318)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:401)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:82)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.handleScheduled(NettyChannelInjector.java:367)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.onMessageScheduled(NettyChannelInjector.java:335)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127)
2016-04-26 19:09:08 [Server thread/WARN] 	at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:193)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.NetworkManager.sendPacket(NetworkManager.java:142)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.PlayerConnection.sendPacket(PlayerConnection.java:1104)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.PlayerChunk.sendChunk(PlayerChunk.java:157)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.PlayerChunk.a(PlayerChunk.java:64)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.PlayerChunkMap.addPlayer(PlayerChunkMap.java:275)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:306)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:382)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:174)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:912)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721)
2016-04-26 19:09:08 [Server thread/WARN] 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620)
2016-04-26 19:09:08 [Server thread/WARN] 	at java.lang.Thread.run(Unknown Source)
[redacted] logged in with entity id 234408 at ([world]586.6487774280399, 40.0, -845.5746598564178)

**Comment by RoboMWM** [comment]
Hmm, when I teleported to those coordinates, I got 

```
2016-04-26 19:42:52 [Server thread/INFO] [RoboMWM: Teleported RoboMWM to 586.5, 40.0, -844.5]
2016-04-26 19:42:53 [Server thread/WARN] java.lang.ArrayIndexOutOfBoundsException

**Comment by Aleksey-Terzi** [comment]
Bug is reproduced and fixed.
You caught this rare case when chunk section (16 x 16 x 16) has more than 127 different block types.
Fix will be available in the next release.

Sources for now committed just to this fork: https://github.com/DevotedMC/Orebfuscator

**Comment by ProgrammerDan** [comment]
@RoboMWM Update to [v4.0.9](https://github.com/lishid/Orebfuscator/releases/tag/v4.0.9) and reopen if this issue fails to fix.
