### ISSUE TITLE
NoSuchMethodError: net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkIfLoaded

### ISSUE THREAD

**Issue by RoboMWM** [lishid/Orebfuscator#84]
Using paper build #717, but doubt it deviates much regarding chunk methods.

```
2016-05-04 15:14:34 [Server thread/ERROR] Could not pass event BlockDamageEvent to Orebfuscator4 v4.0.9-SNAPSHOT
java.lang.NoSuchMethodError: net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkIfLoaded(II)Lnet/minecraft/server/v1_9_R1/Chunk;
	at com.lishid.orebfuscator.internal.MinecraftInternals.getBlockData(MinecraftInternals.java:98) ~[?:?]
	at com.lishid.orebfuscator.internal.MinecraftInternals.getBlockInfo(MinecraftInternals.java:62) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.BlockUpdate.GetAjacentBlocks(BlockUpdate.java:120) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.BlockUpdate.Update(BlockUpdate.java:69) ~[?:?]
	at com.lishid.orebfuscator.obfuscation.BlockUpdate.Update(BlockUpdate.java:47) ~[?:?]
	at com.lishid.orebfuscator.listeners.OrebfuscatorBlockListener.onBlockDamage(OrebfuscatorBlockListener.java:60) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor12.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.2.jar:git-Paper-717]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.2.jar:git-Paper-717]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.2.jar:git-Paper-717]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.2.jar:git-Paper-717]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.2.jar:git-Paper-717]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callBlockDamageEvent(CraftEventFactory.java:267) [patched_1.9.2.jar:git-Paper-717]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:179) [patched_1.9.2.jar:git-Paper-717]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:833) [patched_1.9.2.jar:git-Paper-717]
	at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [patched_1.9.2.jar:git-Paper-717]
	at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [patched_1.9.2.jar:git-Paper-717]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-717]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-717]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:813) [patched_1.9.2.jar:git-Paper-717]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-717]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-717]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-717]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_72]

**Comment by ProgrammerDan** [comment]
Aleks has a fix for this, I'll be releasing it tonight.

**Comment by CeIebrimbor** [comment]
Oh...I just posted the same error. Will take down.

**Comment by ProgrammerDan** [comment]
Sorry for the delay on release, please use this jar and reopen if the issue still exists:

https://github.com/lishid/Orebfuscator/releases/tag/v4.0.10
