### ISSUE TITLE
4.0.9 new errors.

### ISSUE THREAD

**Issue by CeIebrimbor** [lishid/Orebfuscator#85]
Running latest PaperSpigot

`04.05 22:28:08 [Server] ERROR Could not pass event BlockBreakEvent to Orebfuscator4 v4.0.9-SNAPSHOT
04.05 22:28:08 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkIfLoaded(II)Lnet/minecraft/server/v1_9_R1/Chunk;
04.05 22:28:08 [Server] INFO at com.lishid.orebfuscator.internal.MinecraftInternals.getBlockData(MinecraftInternals.java:98) ~[?:?]
04.05 22:28:08 [Server] INFO at com.lishid.orebfuscator.internal.MinecraftInternals.getBlockInfo(MinecraftInternals.java:62) ~[?:?]
04.05 22:28:08 [Server] INFO at com.lishid.orebfuscator.obfuscation.BlockUpdate.GetAjacentBlocks(BlockUpdate.java:120) ~[?:?]
04.05 22:28:08 [Server] INFO at com.lishid.orebfuscator.obfuscation.BlockUpdate.Update(BlockUpdate.java:69) ~[?:?]
04.05 22:28:08 [Server] INFO at com.lishid.orebfuscator.obfuscation.BlockUpdate.Update(BlockUpdate.java:47) ~[?:?]
04.05 22:28:08 [Server] INFO at com.lishid.orebfuscator.listeners.OrebfuscatorBlockListener.onBlockBreak(OrebfuscatorBlockListener.java:42) ~[?:?]
04.05 22:28:08 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor91.execute(Unknown Source) ~[?:?]
04.05 22:28:08 [Server] INFO at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:847) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
04.05 22:28:08 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:813) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-717]
04.05 22:28:08 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]`

**Comment by CeIebrimbor** [comment]
Duplicate of previously reported error.
