### ISSUE TITLE
1.10 error

### ISSUE THREAD

**Issue by Liphius** [lishid/Orebfuscator#88]
[19:47:46] [Netty Epoll Server IO #0/ERROR]: [Orebfuscator4] Unhandled exception number 32 occured in onPacketReceiving(PacketEvent) for Orebfuscator4
java.lang.IllegalArgumentException: No enum constant com.comphenix.protocol.wrappers.EnumWrappers.PlayerDigType.SWAP_HELD_ITEMS
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_74]
at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:527) ~[ProtocolLib%20(2).jar:3.7.0-BETA]
at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:516) ~[ProtocolLib%20(2).jar:3.7.0-BETA]
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[ProtocolLib%20(2).jar:3.7.0-BETA]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib%20(2).jar:3.7.0-BETA]
at com.lishid.orebfuscator.hook.ProtocolLibHook$2.onPacketReceiving(ProtocolLibHook.java:72) ~[orebfuscator-4.0.10-SNAPSHOT.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib%20(2).jar:3.7.0-BETA]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib%20(2).jar:3.7.0-BETA]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:639) [ProtocolLib%20(2).jar:3.7.0-BETA]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:606) [ProtocolLib%20(2).jar:3.7.0-BETA]
at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:332) [ProtocolLib%20(2).jar:3.7.0-BETA]
at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:297) [ProtocolLib%20(2).jar:3.7.0-BETA]
at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:546) [ProtocolLib%20(2).jar:3.7.0-BETA]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-1480adb-6e527e5]
at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:278) [ProtocolLib%20(2).jar:3.7.0-BETA]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot.jar:git-Spigot-1480adb-6e527e5]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-1480adb-6e527e5]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[19:47:49] [Async Chat Thread - #72/INFO]: <Blacksmith Bruce5002> where exactly did you get the nick Con from?
[19:48:00] [Async Chat Thread - #72/INFO]: <

**Comment by RoboMWM** [comment]
Update to 4.0.0, as stated: https://www.spigotmc.org/resources/protocollib.1997/

**Comment by ProgrammerDan** [comment]
Closing this for now; if after updating to 4.0.0 the issue persists, please reopen.
